version: "3.8"

services:

  app:
    container_name: app
    build: .
    command: bash -c "alembic upgrade head && daphne -p 8000 -b 0.0.0.0 app.main:fastapi_app"

    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always