"""New Migration

Revision ID: 2bb44b547ad4
Revises: c4824474863a
Create Date: 2023-08-20 05:50:01.830827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb44b547ad4'
down_revision = 'c4824474863a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('antagonists', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hormones', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hormones')
    op.drop_column('users', 'antagonists')
    op.drop_column('users', 'plan_type')
    # ### end Alembic commands ###
