"""New Migration

Revision ID: b8124593c63b
Revises: 2bb44b547ad4
Create Date: 2023-08-21 16:02:17.504267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8124593c63b'
down_revision = '2bb44b547ad4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('force_logout', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'force_logout')
    # ### end Alembic commands ###
